export default {
  searchParameters: {
    index: 'instant_search',
    query: 'iphone',
    facets: [],
    disjunctiveFacets: [],
    hierarchicalFacets: [
      {
        name: 'brand',
        attributes: ['brand'],
      },
    ],
    facetsRefinements: {},
    facetsExcludes: {},
    disjunctiveFacetsRefinements: {},
    numericRefinements: {},
    tagRefinements: [],
    hierarchicalFacetsRefinements: {
      brand: ['Apple'],
    },
    hitsPerPage: 3,
    maxValuesPerFacet: 20,
    page: 0,
  },
  searchResults: {
    _rawResults: [
      {
        hits: [
          {
            name: 'Apple - iPhone SE 16GB - Space Gray (Verizon)',
            description:
              'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            brand: 'Apple',
            categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
            hierarchicalCategories: {
              lvl0: 'Cell Phones',
              lvl1: 'Cell Phones > iPhone',
              lvl2: 'Cell Phones > iPhone > iPhone SE',
            },
            type: 'Vzw iphone handset',
            price: 449.99,
            price_range: '200 - 500',
            image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005506_sb.jpg',
            url: 'https://api.bestbuy.com/click/-/5005506/pdp',
            free_shipping: true,
            rating: 4,
            popularity: 19581,
            objectID: '5005506',
            _highlightResult: {
              name: {
                value: 'Apple - <em>iPhone</em> SE 16GB - Space Gray (Verizon)',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              description: {
                value:
                  '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              brand: {
                value: 'Apple',
                matchLevel: 'none',
                matchedWords: [],
              },
              categories: [
                {
                  value: 'Cell Phones',
                  matchLevel: 'none',
                  matchedWords: [],
                },
                {
                  value: '<em>iPhone</em>',
                  matchLevel: 'full',
                  fullyHighlighted: true,
                  matchedWords: ['iphone'],
                },
                {
                  value: '<em>iPhone</em> SE',
                  matchLevel: 'full',
                  fullyHighlighted: false,
                  matchedWords: ['iphone'],
                },
              ],
              type: {
                value: 'Vzw <em>iphone</em> handset',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
            },
          },
          {
            name: 'Apple - iPhone SE 64GB - Space Gray (AT&T)',
            description:
              'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            brand: 'Apple',
            categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
            hierarchicalCategories: {
              lvl0: 'Cell Phones',
              lvl1: 'Cell Phones > iPhone',
              lvl2: 'Cell Phones > iPhone > iPhone SE',
            },
            type: 'At&#38;t iphone handset',
            price: 499.99,
            price_range: '200 - 500',
            image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005675_sb.jpg',
            url: 'https://api.bestbuy.com/click/-/5005675/pdp',
            free_shipping: true,
            rating: 4,
            popularity: 19311,
            objectID: '5005675',
            _highlightResult: {
              name: {
                value: 'Apple - <em>iPhone</em> SE 64GB - Space Gray (AT&T)',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              description: {
                value:
                  '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              brand: {
                value: 'Apple',
                matchLevel: 'none',
                matchedWords: [],
              },
              categories: [
                {
                  value: 'Cell Phones',
                  matchLevel: 'none',
                  matchedWords: [],
                },
                {
                  value: '<em>iPhone</em>',
                  matchLevel: 'full',
                  fullyHighlighted: true,
                  matchedWords: ['iphone'],
                },
                {
                  value: '<em>iPhone</em> SE',
                  matchLevel: 'full',
                  fullyHighlighted: false,
                  matchedWords: ['iphone'],
                },
              ],
              type: {
                value: 'At&t <em>iphone</em> handset',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
            },
          },
          {
            name: 'Apple - iPhone SE 16GB - Space Gray (Sprint)',
            description:
              'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            brand: 'Apple',
            categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
            hierarchicalCategories: {
              lvl0: 'Cell Phones',
              lvl1: 'Cell Phones > iPhone',
              lvl2: 'Cell Phones > iPhone > iPhone SE',
            },
            type: 'Spr iphone handset',
            price: 449.99,
            price_range: '200 - 500',
            image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005532_sb.jpg',
            url: 'https://api.bestbuy.com/click/-/5005532/pdp',
            free_shipping: true,
            rating: 4,
            popularity: 19206,
            objectID: '5005532',
            _highlightResult: {
              name: {
                value: 'Apple - <em>iPhone</em> SE 16GB - Space Gray (Sprint)',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              description: {
                value:
                  '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
              brand: {
                value: 'Apple',
                matchLevel: 'none',
                matchedWords: [],
              },
              categories: [
                {
                  value: 'Cell Phones',
                  matchLevel: 'none',
                  matchedWords: [],
                },
                {
                  value: '<em>iPhone</em>',
                  matchLevel: 'full',
                  fullyHighlighted: true,
                  matchedWords: ['iphone'],
                },
                {
                  value: '<em>iPhone</em> SE',
                  matchLevel: 'full',
                  fullyHighlighted: false,
                  matchedWords: ['iphone'],
                },
              ],
              type: {
                value: 'Spr <em>iphone</em> handset',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['iphone'],
              },
            },
          },
        ],
        nbHits: 207,
        page: 0,
        nbPages: 69,
        hitsPerPage: 3,
        processingTimeMS: 1,
        facets: {
          brand: {
            Apple: 207,
          },
        },
        exhaustiveFacetsCount: true,
        exhaustiveNbHits: true,
        query: 'iphone',
        params:
          'query=iphone&hitsPerPage=3&maxValuesPerFacet=20&page=0&facets=%5B%22brand%22%2C%22brand%22%5D&tagFilters=&facetFilters=%5B%5B%22brand%3AApple%22%5D%5D',
        index: 'instant_search',
      },
      {
        hits: [
          {
            objectID: '5005506',
          },
        ],
        nbHits: 3977,
        page: 0,
        nbPages: 1000,
        hitsPerPage: 1,
        processingTimeMS: 4,
        facets: {
          brand: {
            Incipio: 306,
            'Insignia™': 208,
            Apple: 207,
            OtterBox: 191,
            Samsung: 166,
            Speck: 147,
            'kate spade new york': 105,
            mophie: 101,
            Spigen: 94,
            ZAGG: 85,
            'Dynex™': 84,
            Tech21: 81,
            Modal: 78,
            Platinum: 78,
            LifeProof: 72,
            Belkin: 55,
            'Case-Mate': 55,
            'Urban Armor Gear': 48,
            BLU: 47,
            Sony: 47,
          },
        },
        exhaustiveFacetsCount: true,
        exhaustiveNbHits: true,
        query: 'iphone',
        params:
          'query=iphone&hitsPerPage=1&maxValuesPerFacet=20&page=0&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&analytics=false&clickAnalytics=false&facets=%5B%22brand%22%5D',
        index: 'instant_search',
      },
    ],
    query: 'iphone',
    hits: [
      {
        name: 'Apple - iPhone SE 16GB - Space Gray (Verizon)',
        description:
          'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
        brand: 'Apple',
        categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
        hierarchicalCategories: {
          lvl0: 'Cell Phones',
          lvl1: 'Cell Phones > iPhone',
          lvl2: 'Cell Phones > iPhone > iPhone SE',
        },
        type: 'Vzw iphone handset',
        price: 449.99,
        price_range: '200 - 500',
        image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005506_sb.jpg',
        url: 'https://api.bestbuy.com/click/-/5005506/pdp',
        free_shipping: true,
        rating: 4,
        popularity: 19581,
        objectID: '5005506',
        _highlightResult: {
          name: {
            value: 'Apple - <em>iPhone</em> SE 16GB - Space Gray (Verizon)',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          description: {
            value:
              '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          brand: {
            value: 'Apple',
            matchLevel: 'none',
            matchedWords: [],
          },
          categories: [
            {
              value: 'Cell Phones',
              matchLevel: 'none',
              matchedWords: [],
            },
            {
              value: '<em>iPhone</em>',
              matchLevel: 'full',
              fullyHighlighted: true,
              matchedWords: ['iphone'],
            },
            {
              value: '<em>iPhone</em> SE',
              matchLevel: 'full',
              fullyHighlighted: false,
              matchedWords: ['iphone'],
            },
          ],
          type: {
            value: 'Vzw <em>iphone</em> handset',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
        },
      },
      {
        name: 'Apple - iPhone SE 64GB - Space Gray (AT&T)',
        description:
          'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
        brand: 'Apple',
        categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
        hierarchicalCategories: {
          lvl0: 'Cell Phones',
          lvl1: 'Cell Phones > iPhone',
          lvl2: 'Cell Phones > iPhone > iPhone SE',
        },
        type: 'At&#38;t iphone handset',
        price: 499.99,
        price_range: '200 - 500',
        image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005675_sb.jpg',
        url: 'https://api.bestbuy.com/click/-/5005675/pdp',
        free_shipping: true,
        rating: 4,
        popularity: 19311,
        objectID: '5005675',
        _highlightResult: {
          name: {
            value: 'Apple - <em>iPhone</em> SE 64GB - Space Gray (AT&T)',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          description: {
            value:
              '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          brand: {
            value: 'Apple',
            matchLevel: 'none',
            matchedWords: [],
          },
          categories: [
            {
              value: 'Cell Phones',
              matchLevel: 'none',
              matchedWords: [],
            },
            {
              value: '<em>iPhone</em>',
              matchLevel: 'full',
              fullyHighlighted: true,
              matchedWords: ['iphone'],
            },
            {
              value: '<em>iPhone</em> SE',
              matchLevel: 'full',
              fullyHighlighted: false,
              matchedWords: ['iphone'],
            },
          ],
          type: {
            value: 'At&t <em>iphone</em> handset',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
        },
      },
      {
        name: 'Apple - iPhone SE 16GB - Space Gray (Sprint)',
        description:
          'iPhone SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
        brand: 'Apple',
        categories: ['Cell Phones', 'iPhone', 'iPhone SE'],
        hierarchicalCategories: {
          lvl0: 'Cell Phones',
          lvl1: 'Cell Phones > iPhone',
          lvl2: 'Cell Phones > iPhone > iPhone SE',
        },
        type: 'Spr iphone handset',
        price: 449.99,
        price_range: '200 - 500',
        image: 'https://cdn-demo.algolia.com/bestbuy-0118/5005532_sb.jpg',
        url: 'https://api.bestbuy.com/click/-/5005532/pdp',
        free_shipping: true,
        rating: 4,
        popularity: 19206,
        objectID: '5005532',
        _highlightResult: {
          name: {
            value: 'Apple - <em>iPhone</em> SE 16GB - Space Gray (Sprint)',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          description: {
            value:
              '<em>iPhone</em> SE features a 4-inch Retina display, an A9 chip with 64-bit desktop-class architecture, the Touch ID fingerprint sensor, a 12MP iSight camera, a FaceTime HD camera with Retina Flash, Live Photos, LTE and fast Wi-Fi, iOS 9, and iCloud.',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
          brand: {
            value: 'Apple',
            matchLevel: 'none',
            matchedWords: [],
          },
          categories: [
            {
              value: 'Cell Phones',
              matchLevel: 'none',
              matchedWords: [],
            },
            {
              value: '<em>iPhone</em>',
              matchLevel: 'full',
              fullyHighlighted: true,
              matchedWords: ['iphone'],
            },
            {
              value: '<em>iPhone</em> SE',
              matchLevel: 'full',
              fullyHighlighted: false,
              matchedWords: ['iphone'],
            },
          ],
          type: {
            value: 'Spr <em>iphone</em> handset',
            matchLevel: 'full',
            fullyHighlighted: false,
            matchedWords: ['iphone'],
          },
        },
      },
    ],
    index: 'instant_search',
    hitsPerPage: 3,
    nbHits: 207,
    nbPages: 69,
    page: 0,
    processingTimeMS: 5,
    exhaustiveFacetsCount: true,
    exhaustiveNbHits: true,
    disjunctiveFacets: [],
    hierarchicalFacets: [
      {
        name: 'brand',
        count: null,
        isRefined: true,
        path: null,
        data: [
          {
            name: 'Apple',
            path: 'Apple',
            count: 207,
            isRefined: true,
            data: null,
          },
          {
            name: 'BLU',
            path: 'BLU',
            count: 47,
            isRefined: false,
            data: null,
          },
          {
            name: 'Belkin',
            path: 'Belkin',
            count: 55,
            isRefined: false,
            data: null,
          },
          {
            name: 'Case-Mate',
            path: 'Case-Mate',
            count: 55,
            isRefined: false,
            data: null,
          },
          {
            name: 'Dynex™',
            path: 'Dynex™',
            count: 84,
            isRefined: false,
            data: null,
          },
          {
            name: 'Incipio',
            path: 'Incipio',
            count: 306,
            isRefined: false,
            data: null,
          },
          {
            name: 'Insignia™',
            path: 'Insignia™',
            count: 208,
            isRefined: false,
            data: null,
          },
          {
            name: 'LifeProof',
            path: 'LifeProof',
            count: 72,
            isRefined: false,
            data: null,
          },
          {
            name: 'Modal',
            path: 'Modal',
            count: 78,
            isRefined: false,
            data: null,
          },
          {
            name: 'OtterBox',
            path: 'OtterBox',
            count: 191,
            isRefined: false,
            data: null,
          },
          {
            name: 'Platinum',
            path: 'Platinum',
            count: 78,
            isRefined: false,
            data: null,
          },
          {
            name: 'Samsung',
            path: 'Samsung',
            count: 166,
            isRefined: false,
            data: null,
          },
          {
            name: 'Sony',
            path: 'Sony',
            count: 47,
            isRefined: false,
            data: null,
          },
          {
            name: 'Speck',
            path: 'Speck',
            count: 147,
            isRefined: false,
            data: null,
          },
          {
            name: 'Spigen',
            path: 'Spigen',
            count: 94,
            isRefined: false,
            data: null,
          },
          {
            name: 'Tech21',
            path: 'Tech21',
            count: 81,
            isRefined: false,
            data: null,
          },
          {
            name: 'Urban Armor Gear',
            path: 'Urban Armor Gear',
            count: 48,
            isRefined: false,
            data: null,
          },
          {
            name: 'ZAGG',
            path: 'ZAGG',
            count: 85,
            isRefined: false,
            data: null,
          },
          {
            name: 'kate spade new york',
            path: 'kate spade new york',
            count: 105,
            isRefined: false,
            data: null,
          },
          {
            name: 'mophie',
            path: 'mophie',
            count: 101,
            isRefined: false,
            data: null,
          },
        ],
      },
      {
        name: 'brand',
        count: null,
        isRefined: true,
        path: null,
        data: null,
      },
    ],
    facets: [],
    _state: {
      index: 'instant_search',
      query: 'iphone',
      facets: [],
      disjunctiveFacets: [],
      hierarchicalFacets: [
        {
          name: 'brand',
          attributes: ['brand'],
        },
        {
          name: 'brand',
          attributes: ['brand'],
        },
      ],
      facetsRefinements: {},
      facetsExcludes: {},
      disjunctiveFacetsRefinements: {},
      numericRefinements: {},
      tagRefinements: [],
      hierarchicalFacetsRefinements: {
        brand: ['Apple'],
      },
      hitsPerPage: 3,
      maxValuesPerFacet: 20,
      page: 0,
    },
  },
};
